image: Visual Studio 2017

init:
  - git --version
  - git config --global core.autocrlf true

install:
  - git clone https://github.com/i3thuan5/weasel.git
  - cd weasel
  - git checkout kai_sanphin_mia

build_script:
  - ps: $OutputEncoding
  - ps: $InputEncoding
  - ps: chcp
  - ps: $OutputEncoding = New-Object System.Text.UTF8Encoding
  - ps: $InputEncoding = New-Object System.Text.UTF8Encoding
  - ps: chcp 65001
  - ps: $OutputEncoding
  - ps: $InputEncoding
  - ps: chcp
  - ps: Get-ChildItem -File -Recurse | Select-String "意傳台語輸入法"
  - ps: $new_app_name="意傳台語輸入法-白話字漢羅"
  - ps: $env:new_app_name=$new_app_name
  - ps: Get-ChildItem -File -Recurse -Include build.bat,install.nsi,*.h,*.hpp,*.cpp,*.rc,*.vcxproj,*.vcxproj.filters -Encoding utf8 | ForEach {(Get-Content $_ -Encoding utf8 | ForEach -Encoding utf8 {$_ -replace  "意傳台語輸入法", $new_app_name}) | Set-Content $_ -Encoding utf8}
  - ps: Get-ChildItem -File -Recurse | Select-String $new_app_name

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
